apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo
      command: ["mongod","--bind_ip_all"]
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: csi-pvc
          mountPath: "/data/db"
  
  volumes:
    - name: nfs-volume
      PersistentVolumeClaim:
      claimName: csi-pvc


apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
spec:
  containers:
    - name: mongo
      image: mongo
      command: ["mongod","--bind_ip_all"]
      ports: 
      - containerPort: 27017
      volumeMounts:
        - name: csi-pvc
          mountPath: /data/db 
  volumes:
    - name: csi-pvc
      persistentVolumeClaim:
        claimName: csi-pvc      